#!/usr/bin/env bash

git-submodule-add() {
    url="$*"
    name=$(basename "$url")
    echo git submodule add "$url" ".vim/bundle-available/$name"
    cd '.vim/bundle/' || exit 1
    ln -s "../bundle-available/$name" .
}

git-submodule-add "$*"
