#!/usr/bin/env bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install \
	bash-completion \
	fpp \
	fzf \
	git \
	gpg \
	ripgrep \
	thefuck \
	tig \
	vim \
	watchman \
	yarn

brew cask install \
    squirrel

# for ycm
yarn global add typescript

curl https://sh.rustup.rs -sSf | sh

git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it &&
	~/.bash_it/install.sh

find . -type f \
	-depth 1 \
	-name '.*' \
	! -name .gitconfig \
	! -name .gitmodules |
	sort |
	sed "s@^.@$PWD@" |
	xargs -I {} ln -s {} ~

cp .gitconfig ~

echo "git config --global user.name '$USER'"
echo "git config --global user.email '$USER@users.noreply.github.com'"
