#!/usr/bin/env bash

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install \
    bash-completion \
    bat \
    fpp \
    fzf \
    git \
    git-crypt \
    gpg \
    jq \
    ncdu \
    noti \
    ripgrep \
    tig \
    vim \
    watchman \
    yarn

brew cask install \
    android-file-transfer \
    clipy \
    firefox \
    gimp \
    google-chrome \
    homebrew/cask-versions/firefox-developer-edition \
    insomnia \
    karabiner-elements \
    keepassxc \
    keybase \
    libreoffice \
    licecap \
    opera \
    # origin \
    postman \
    skype \
    spectacle \
    squirrel \
    steam \
    syncthing-macos \
    tor-browser \
    vagrant \
    virtualbox \
    virtualbox-extension-pack

yarn global add \
    tldr \
    typescript # for YouCompleteMe

curl https://sh.rustup.rs -sSf | sh

git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it &&
    ~/.bash_it/install.sh

find . -type f \
    -depth 1 \
    -name '.*' \
    ! -name .gitconfig \
    ! -name .gitmodules |
    sort |
    sed "s@^.@$PWD@" |
    xargs -I {} ln -s {} ~

cp .gitconfig ~

vim -S ~/.vim/snapshot.vim

echo "git config --global user.name '$USER'"
echo "git config --global user.email '$USER@users.noreply.github.com'"
