#!/usr/bin/env bash

# Go Mono https://blog.golang.org/go-fonts#TOC_2.

main() {
    if [ $# != 1 ]; then
        echo "Usage: $0 <git_global_config_user.signingkey>"
        return 1
    fi

    signingkey=$1

    IFS='<' read -r name email <<< "$(gpg --list-key "$signingkey" | sed -n 's/uid           \[ultimate\] //; 3s/>//g; 3s/ </</; 3p')"

    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    brew install \
        autojump \
        cask-repair \
        ctags \
        direnv \
        elixir \
        erlang \
        fd \
        fzf \
        git \
        git-crypt \
        gitlab-gem \
        gnupg \
        hr \
        hub \
        jq \
        mas \
        ncdu \
        node \
        node@10 \
        noti \
        ripgrep \
        rmtrash \
        screen \
        shellcheck \
        shfmt \
        tig \
        tldr \
        typescript \
        vim \
        watchman

    # brew install \
    #     asciinema \
    #     bat \
    #     exercism \
    #     fpp \
    #     gitup \
    #     nnn \
    #     octave \
    #     phantomjs \
    #     python-yq \
    #     surfraw \
    #     todo-txt \
    #     w3m \
    #     zbar

    # brew tap browsh-org/homebrew-browsh && \
    #     brew install browsh-org/browsh/browsh

    brew cask install \
        chromedriver \
        chromium \
        clipy \
        drawio \
        dropbox \
        firefox \
        firefox-developer-edition \
        gimp \
        insomnia \
        karabiner-elements \
        keepassxc \
        keybase \
        mongodb-compass-community \
        postman \
        remember-the-milk \
        slack \
        spectacle \
        vagrant \
        virtualbox \
        zoho-mail \
        zoomus

    brew cask install \
        adobe-acrobat-reader \
        anki \
        brave-browser \
        libreoffice \
        notion \
        opera \
        operadriver \
        origin \
        polar-bookshelf \
        rescuetime \
        skype \
        steam \
        syncthing-app \
        toggl \
        tor-browser \
        virtualbox-extension-pack \
        vivaldi

    # brew cask install \
    #     android-file-transfer \
    #     devdocs \
    #     google-chrome \
    #     mongodb-compass \
    #     mongodb-compass-isolated-edition \
    #     mongodb-compass-readonly \
    #     quicklook-json \
    #     robo-3t \
    #     squirrel \
    #     studio-3t \


    mas install \
    # com.rockysandstudio.Battery-Diag (2.4.3)
        836505650 \
    # com.fasthatchapps.gifgrabberosx (4.1)
        # 668208984 \
    # jp.naver.line.mac (5.16.2)
        539883307 \
    # app.metacode.metacode (1.8.15)
        1454994142 \
    # com.readitlater.PocketMac (1.8.2)
        568494494 \
    # me.alvinzhu.Thor (1.3.1)
        1120999687

    curl https://sh.rustup.rs -sSf | sh

    git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it &&
        ~/.bash_it/install.sh

    bash-it enable alias \
        docker \
        docker-compose \
        general \
        git \
        homebrew \
        homebrew-cask \
        npm \
        osx \
        todo.txt-cli \
        vagrant \
        yarn

    bash-it enable completion \
        brew \
        docker \
        docker-compose \
        docker-machine \
        git \
        makefile \
        npm \
        ssh \
        system \
        todo \
        vagrant

    bash-it enable plugin \
        autojump \
        direnv \
        extract \
        fzf \
        git \
        todo

    find . \
        -depth 1 \
        -name '.*' \
        ! -name .git \
        ! -name .gitconfig \
        ! -name .gitmodules \
        ! -name .todo |
        sort |
        sed "s@^.@$PWD@" |
        xargs -I {} ln -fs {} ~

    mkdir -p ~/.gnupg/ && ln -fs "$PWD/.gnupg/gpg-agent.conf" ~/.gnupg/gpg-agent.conf
    mkdir -p ~/.todo/ && ln -fs "$PWD/.todo/config" ~/.todo/config

    cp .gitconfig ~

    mkdir -p ~/.cache/vim-gutentags

    vim -S ~/.vim/snapshot.vim

    git config --global user.email "$email"
    git config --global user.name "$name"
    git config --global user.signingkey "$signingkey"
    git config --global --list
}

main "$*"

echo 'REMEMBER:'
echo '- Automatically rearrange Spaces based on most recent use'
echo '- Dashboard: As Overlay'
