gpg-agent:
    config:
        keys:
            # Remember your master password for up to two hours.
            # Every time you decrypt a password within this two-hour timespan,
            # the timer will reset.
            default-cache-ttl: 7200
            # This is the maximum amount of time gpg-agent will remember your master password.
            # Once this eight hours has expired, gpg-agent will always ask you to re-enter it.
            max-cache-ttl: 28800
