---
matches:

  - trigger: As,.
    replace: App Store

  - trigger: Pwa,.
    replace: Progressive Web Application

  - trigger: Spa,.
    replace: Single Page Application

  - trigger: app,.
    replace: application
