# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
show_icon: false
matches:
  - trigger: "0,."
    replace: "0.0.0.0"
  - trigger: "23,."
    replace: "23:59"
  - trigger: "e,."
    replace: "example.com"
  - trigger: "thowt,."
    replace: "A penny for your thoughts."

  - trigger: "\\d,."
    replace: "{{d}}"
    vars:
      - name: d
        type: shell
        params:
          cmd: "pbpaste | sed 's/[^[:digit:].]//g'"
