#!/usr/bin/env sh

[ -n "$SET_X" ] && set -x

color() {
  cat <<'EOF' | sed 's#......$#https://www.color-hex.com/color/&#' | grep -i "${@:-""}"
粉紅色系	MediumVioletRed     	中紫羅蘭紅  	C71585
粉紅色系	DeepPink            	深粉        	FF1493
粉紅色系	PaleVioletRed       	蒼紫羅蘭紅  	DB7093
粉紅色系	HotPink             	熱情粉紅    	FF69B4
粉紅色系	LightPink           	淺粉        	FFB6C1
粉紅色系	Pink                	粉紅        	FFC0CB
紅色系  	DarkRed             	深紅        	8B0000
紅色系  	Red                 	純紅        	FF0000
紅色系  	FireBrick           	火磚色      	B22222
紅色系  	Crimson             	緋紅色      	DC143C
紅色系  	IndianRed           	印度紅      	CD5C5C
紅色系  	LightCoral          	淡珊瑚色    	F08080
紅色系  	Salmon              	鮭魚色      	FA8072
紅色系  	DarkSalmon          	深鮭魚色    	E9967A
紅色系  	LightSalmon         	淺鮭魚色    	FFA07A
橙色系  	OrangeRed           	橙紅        	FF4500
橙色系  	Tomato              	番茄色      	FF6347
橙色系  	DarkOrange          	深橙        	FF8C00
橙色系  	Coral               	珊瑚色      	FF7F50
橙色系  	Orange              	橙色        	FFA500
黃色系  	DarkKhaki           	深卡其布色  	BDB76B
黃色系  	Gold                	金色        	FFD700
黃色系  	Khaki               	卡其布色    	F0E68C
黃色系  	PeachPuff           	桃色        	FFDAB9
黃色系  	Yellow              	純黃        	FFFF00
黃色系  	PaleGoldenrod       	灰秋麒麟色  	EEE8AA
黃色系  	Moccasin            	鹿皮鞋色    	FFE4B5
黃色系  	PapayaWhip          	番木瓜色    	FFEFD5
黃色系  	LightGoldenrodYellow	淺秋麒麟黃  	FAFAD2
黃色系  	LemonChiffon        	檸檬薄紗    	FFFACD
黃色系  	LightYellow         	淺黃        	FFFFE0
褐色系  	Maroon              	栗色        	800000
褐色系  	Brown               	純褐        	A52A2A
褐色系  	SaddleBrown         	鞍褐色      	8B4513
褐色系  	Sienna              	赭黃        	A0522D
褐色系  	Chocolate           	巧克力色    	D2691E
褐色系  	DarkGoldenrod       	深金菊色    	B8860B
褐色系  	Peru                	秘魯色      	CD853F
褐色系  	RosyBrown           	玫瑰金      	BC8F8F
褐色系  	Goldenrod           	金菊色      	DAA520
褐色系  	SandyBrown          	沙褐        	F4A460
褐色系  	Tan                 	棕褐        	D2B48C
褐色系  	BurlyWood           	硬木色      	DEB887
褐色系  	Wheat               	小麥色      	F5DEB3
褐色系  	NavajoWhite         	納瓦霍白    	FFDEAD
褐色系  	Bisque              	濃湯色      	FFE4C4
褐色系  	BlanchedAlmond      	白杏仁色    	FFEBCD
褐色系  	Cornsilk            	玉米絲色    	FFF8DC
紫色系  	Indigo              	靛青        	4B0082
紫色系  	RebeccaPurple       	麗碧卡紫    	663399
紫色系  	Purple              	宗主教紫    	800080
紫色系  	DarkMagenta         	深洋紅      	8B008B
紫色系  	DarkViolet          	深紫羅蘭色  	9400D3
紫色系  	DarkSlateBlue       	深岩暗藍灰  	483D8B
紫色系  	BlueViolet          	深紫羅蘭藍  	8A2BE2
紫色系  	DarkOrchid          	深蘭花紫    	9932CC
紫色系  	Fuchsia             	品紅色      	FF00FF
紫色系  	Magenta             	洋紅色      	FF00FF
紫色系  	SlateBlue           	板岩暗藍灰  	6A5ACD
紫色系  	MediumSlateBlue     	中板岩暗藍灰	7B68EE
紫色系  	MediumOrchid        	中蘭花紫    	BA55D3
紫色系  	MediumPurple        	中紫        	9370DB
紫色系  	Orchid              	蘭花紫      	DA70D6
紫色系  	Violet              	紫羅蘭色    	EE82EE
紫色系  	Plum                	李子色      	DDA0DD
紫色系  	Thistle             	薊色        	D8BFD8
紫色系  	Lavender            	淡薰衣草紫  	E6E6FA
藍色系  	MidnightBlue        	午夜藍      	191970
藍色系  	Navy                	海軍藍      	000080
藍色系  	DarkBlue            	深藍        	00008B
藍色系  	MediumBlue          	中藍        	0000CD
藍色系  	Blue                	純藍        	0000FF
藍色系  	RoyalBlue           	寶藍        	4169E1
藍色系  	SteelBlue           	鋼藍        	4682B4
藍色系  	DodgerBlue          	道奇藍      	1E90FF
藍色系  	DeepSkyBlue         	深天藍      	00BFFF
藍色系  	CornflowerBlue      	矢車菊藍    	6495ED
藍色系  	SkyBlue             	天藍        	87CEEB
藍色系  	LightSkyBlue        	淡天藍      	87CEFA
藍色系  	LightSteelBlue      	淡鋼藍      	B0C4DE
藍色系  	LightBlue           	淡藍        	ADD8E6
藍色系  	PowderBlue          	粉藍        	B0E0E6
青色系  	Teal                	鴨綠色      	008080
青色系  	DarkCyan            	深青        	008B8B
青色系  	LightSeaGreen       	淺海洋綠    	20B2AA
青色系  	CadetBlue           	學員藍      	5F9EA0
青色系  	DarkTurquoise       	深綠松石色  	00CED1
青色系  	MediumTurquoise     	中綠松石色  	48D1CC
青色系  	Turquoise           	綠松石色    	40E0D0
青色系  	Aqua                	水色        	00FFFF
青色系  	Cyan                	青色        	00FFFF
青色系  	Aquamarine          	碧藍        	7FFFD4
青色系  	PaleTurquoise       	蒼綠松石色  	AFEEEE
青色系  	LightCyan           	淺青色      	E0FFFF
綠色系  	DarkGreen           	深綠色      	006600
綠色系  	Green               	純綠        	008000
綠色系  	DarkOliveGreen      	深橄欖綠    	556B2F
綠色系  	ForestGreen         	森林綠      	228B22
綠色系  	SeaGreen            	海洋綠      	2E8B57
綠色系  	Olive               	橄欖色      	808000
綠色系  	OliveDrab           	橄欖土褐    	6B8E23
綠色系  	MediumSeaGreen      	中海洋綠    	3CB371
綠色系  	LimeGreen           	萊姆綠      	32CD32
綠色系  	LimeGreen           	檸檬綠      	32CD32
綠色系  	Lime                	蘋果綠      	00FF00
綠色系  	Lime                	萊姆色      	00FF00
綠色系  	Lime                	青檸綠      	00FF00
綠色系  	SpringGreen         	春綠        	00FF7F
綠色系  	MediumSpringGreen   	中春綠      	00FA9A
綠色系  	DarkSeaGreen        	深海洋綠    	8FBC8F
綠色系  	MediumAquamarine    	中碧藍      	66CDAA
綠色系  	YellowGreen         	黃綠        	9ACD32
綠色系  	LawnGreen           	草坪綠      	7CFC00
綠色系  	Chartreuse          	查特酒綠    	7FFF00
綠色系  	LightGreen          	淡綠        	90EE90
綠色系  	GreenYellow         	綠黃        	ADFF2F
綠色系  	PaleGreen           	蒼綠        	98FB98
白色系  	MistyRose           	霧玫瑰色    	FFE4E1
白色系  	AntiqueWhite        	古董白      	FAEBD7
白色系  	Linen               	亞麻白      	FAF0E6
白色系  	Beige               	米白        	F5F5DC
白色系  	WhiteSmoke          	煙燻白      	F5F5F5
白色系  	LavenderBlush       	薰衣草紫紅  	FFF0F5
白色系  	OldLace             	舊蕾絲白    	FDF5E6
白色系  	AliceBlue           	愛麗絲藍    	F0F8FF
白色系  	Seashell            	貝殼白      	FFF5EE
白色系  	GhostWhite          	幽靈白      	F8F8FF
白色系  	Honeydew            	哈密瓜色    	F0FFF0
白色系  	FloralWhite         	花白        	FFFAF0
白色系  	Azure               	天藍霧      	F0FFFF
白色系  	MintCream           	薄荷奶油色  	F5FFFA
白色系  	Snow                	雪白        	FFFAFA
白色系  	Ivory               	象牙白      	FFFFF0
白色系  	White               	純白        	FFFFFF
黑灰色系	Black               	純黑        	000000
黑灰色系	DarkSlateGray       	深岩灰      	2F4F4F
黑灰色系	DimGray             	昏灰        	696969
黑灰色系	SlateGray           	岩灰        	708090
黑灰色系	Gray                	純灰        	808080
黑灰色系	LightSlateGray      	淡岩灰      	778899
黑灰色系	DarkGray            	深灰        	A9A9A9
黑灰色系	Silver              	純銀        	C0C0C0
黑灰色系	LightGray           	淡灰        	D3D3D3
黑灰色系	Gainsboro           	庚斯博羅灰  	DCDCDC
EOF
}

color "$@"
