# https://starship.rs/config/#git-metrics
[[battery.display]]
charging_symbol = '🔌'
discharging_symbol = '🔋'
threshold = 95
# [git_metrics]
# [kubernetes]
# [localip]
# [memory_usage]
# [hg_branch]
# [os]
# [pijul_channel]
# [shell]
# [shlvl]
# [status]
# [sudo]

# https://starship.rs/config/#os
[os]
format = '[$symbol]($style)'
disabled = false

# https://starship.rs/config/#time
[time]
disabled = false
format = '[$time]($style) '
time_format = '%FT%T%z'
# disabled = false
