#!/usr/bin/env sh

# Follow fugitive-:Gstatus
# alias gca='git commit --amend'
# alias gcc='git commit -v'
# alias gce='git commit --amend --no-edit'
# alias gcw='git commit --amend --only'
# alias gcva='git commit --verbose --amend'
# alias gcvc='git commit --verbose'

# alias g='tig'
# alias gr='tig refs'

# Enhancement

# alias gl='git pull --prune'

# alias ga.='git add .'
# alias ga='git commit --message "Apply $(fc -ln -1 | xargs)"'
# alias gap='git add -p'
# alias gau='git add --update'
# alias gamscp='git am --show-current-patch'
# alias gbb='git bisect bad'
# alias gbg='git bisect good'
# alias gbr='hub browse'
# alias gbs='git bisect start'
# alias gbrs='git bisect reset'
# alias gc='git commit --edit --file=.git/COMMIT_EDITMSG '
# alias gcm='git commit -m'
# alias gcem='git commit --allow-empty --message'
# alias gcf='git commit --fixup'
# alias gcfh='git commit --fixup HEAD'
# alias gci='git check-ignore'
# alias gcs='git commit --squash'
# alias gcsh='git commit --squash HEAD'
# alias gcl1='git clone --depth=1'
# alias gco-='git checkout -'
# alias gco.='git checkout .'
# alias gcoo='git checkout --ours'
# alias gcoom='git checkout origin/master'
# alias gcobu='git checkout -b "$(git config user.email | cut -d@ -f1)/$(git symbolic-ref --short HEAD | cut -d"/" -f2)"'
# alias gcobu='git checkout "$(git config user.email | cut -d@ -f1)/$(git symbolic-ref --short HEAD | cut -d"/" -f2)"'
# alias gcop='git checkout -p'
# alias gcot='git checkout --theirs'
# alias gcv='git cherry -v'
# alias gcrm='git commit --reuse-message'
# alias gcrmh='git commit --reuse-message HEAD'
# alias gd='git diff --patch-with-stat '
# alias gdi='git diff --patch-with-stat --ignore-space-change'
# alias gds='git diff --patch-with-stat --staged'
# alias gdsi='git diff --patch-with-stat --staged --ignore-space-change'
# alias gga='git log --graph --pretty=format:"%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(cyan)(%cr)%Creset" --abbrev-commit --date=relative --all'
# alias ggr='git grep'
# alias gia='git init && git commit --allow-empty --message "Initialize empty Git repository" && git add . && git commit'
# alias gic='git init && git commit --allow-empty --message "Initialize empty Git repository"'
# alias gmt='git mergetool'
# alias gpof='git push origin -f'
# alias gpoh='git push origin HEAD:'
# alias gpohm='git push origin HEAD:master'
# alias gpuo='git push --set-upstream origin "$(git rev-parse --abbrev-ref HEAD)" '
# alias gpuof='git push --set-upstream origin "$(git rev-parse --abbrev-ref HEAD)" --force'
# alias glla='git log --graph --pretty=oneline --abbrev-commit --all'
# alias grb='git rebase'
# alias grb='git rebase'
# alias grba='git rebase --abort'
# alias grbc='git rebase --continue'
# alias grbi='git rebase --interactive'
# alias grbk='git rebase --skip'
# alias grbm='git rebase origin/master'
# alias grbo='git rebase --onto'
# alias grboh='git rebase `git symbolic-ref refs/remotes/origin/HEAD`'
# alias grbs='git rebase --autosquash --interactive'
# alias grbdb='git fetch --all --prune && git rebase origin/$DEFAULT_BRANCH'
# alias grbu='git fetch origin -v; git fetch upstream -v; git merge upstream/master'
# alias grl='git reflog --date=relative'
# alias grm='git rm'
# alias grs^='git reset HEAD^'
# alias grsh='git reset --hard'
# alias grsm='git reset --merge'
# alias grvt='git revert'
# alias grvtm1='git revert --mainline 1'
# alias grvtm2='git revert --mainline 2'
# alias gsh='git show --patch-with-stat '
# alias gshi='git show --patch-with-stat --ignore-space-change '
# alias gsta='git stash push && git stash apply'
# alias gstd='git stash drop'
# alias gstk='git stash --keep-index'
# alias gstP='git stash pop'
# alias gstp='git stash push'
# alias gsts='git stash show --patch-with-stat '
# alias gstsi='git stash show --patch-with-stat --ignore-space-change '
# unalias gh
# alias gcd='cd "$(git rev-parse --show-toplevel)"'
