#!/usr/bin/env sh

# alias na='npm audit'
# alias naf='npm audit fix'
# alias nci='npm ci'
# alias ncl='rm -fr ./node_modules'
# alias ngi='npm --global install'
# alias ngls='npm --global list --depth=0'
# alias ngrm='npm --global rm'
# alias nin='npm init '
# alias ni='npm install '
# alias nid='npm install --save-dev'
# alias niy='npm init --yes'
# alias nins='npm install --no-save'
# alias npg='npm pkg get '
# alias nps='npm pkg set '
# alias nrb='npm run build'
# alias nrm='npm rm'
# alias nrs='npm run --silent'
# alias ns='npm start'
# alias nsr='npm search'
# alias nt='npm test'
# alias nv='npm view'

# alias pje='jq $". + { \"engines\": { \"node\": \"^$(node -v | cut -c2-)\", \"npm\": \"^$(npm -v)\" } }" <<< "$(cat package.json)" > package.json'
# alias pjp='jq $". + { \"private\": true }" <<< "$(cat package.json)" > package.json'
