#!/usr/bin/env bash

alias dkbasename='echo $(basename $PWD | tr "[:upper:]" "[:lower:]")'
alias dkb='docker build --tag ${USER}/$(dkbasename) .'
alias dkbr='docker run --interactive --name ${USER}_$(dkbasename) --rm --tty ${USER}/$(basename $PWD)'
alias dkbri='docker rmi ${USER}/$(dkbasename)'
alias dkbrw='docker run --interactive --name ${USER}_$(dkbasename) --rm --tty --volume $PWD:$PWD --workdir $PWD ${USER}/$(basename $PWD)'
alias dkbs='docker stop ${USER}_$(dkbasename)'
alias dkrr='docker run --interactive --rm --tty --volume $PWD:$PWD --workdir $PWD'
alias dkru='docker run --interactive --rm --tty --user $UID:$(id -g) --volume $PWD:$PWD --workdir $PWD'

alias dkri='docker rmi'
alias dkrm='docker rm'
alias dkrmf='docker rm --force'
alias dks='docker stop'
alias dkvl='docker volume ls'
alias dkvr='docker volume rm'
alias dkt='docker tag'
alias dkp='docker push'
alias dksd='docker system df'

alias bfg='docker run --interactive --rm --tty --volume $PWD:/home/nikovirtala nikovirtala/bfg'
alias gcloud='docker run --interactive --tty --name gcloud-config google/cloud-sdk:alpine gcloud'
alias gsutil'docker run --interactive --rm --tty --volumes-from gcloud-config google/cloud-sdk:alpine gsutil'
alias http='docker run --rm alpine/httpie'
alias mitmproxy='docker run --interactive --rm --tty --publish 8080:8080 --publish 127.0.0.1:8081:8081 mitmweb --web-iface 0.0.0.0'
alias mitmproxyv='docker run --interactive --rm --tty --publish 8080:8080 --publish 127.0.0.1:8081:8081 --volume ~/.mitmproxy:/home/mitmproxy/.mitmproxy mitmproxy/mitmproxy mitmweb --web-iface 0.0.0.0'
alias mongo='docker run --interactive --rm --tty mongo mongo'
alias now='docker run --rm --volume "$PWD/root/.now:/root/.now" smutdose/now'
alias speedtest-cli='docker run --rm moutten/speedtest-cli'
alias swagger-codegen='docker run --rm --volume ${PWD}:/${PWD} --workdir ${PWD} swaggerapi/swagger-codegen-cli generate'
alias swagger-codegenes='docker run --rm --volume ${PWD}:/${PWD} --workdir ${PWD} swaggerapi/swagger-codegen-cli generate --lang=javascript --additional-properties=usePromises=true,useES6=true'
alias swagger-codegenjs='docker run --rm --volume ${PWD}:/${PWD} --workdir ${PWD} swaggerapi/swagger-codegen-cli generate --lang=javascript --additional-properties=usePromises=true'
alias toodles='docker run --interactive --rm --tty --publish 9001:9001 --volume $PWD:/repo aviaviavi/toodles'
alias variety='docker run --rm objectrocket/variety'
alias wraith='docker run --rm bbcnews/wraith'
