#!/usr/bin/env bash

alias dk="docker"
alias dkb='docker build --tag ${USER}/$(dkbasename) .'
alias dkbasename='echo $(basename $PWD | tr "[:upper:]" "[:lower:]")'
alias dkbr='docker run --interactive --name ${USER}_$(dkbasename) --rm --tty ${USER}/$(basename $PWD)'
alias dkbrw='docker run --interactive --name ${USER}_$(dkbasename) --rm --tty --volume $PWD:$PWD --workdir $PWD ${USER}/$(basename $PWD)'
alias dkbs='docker stop ${USER}_$(dkbasename)'
alias dkbri='docker rmi ${USER}/$(dkbasename)'
alias dkrr='docker run --interactive --rm --tty --volume $PWD:$PWD --workdir $PWD'
alias dkru='docker run --interactive --rm --tty --user $UID:$(id -g) --volume $PWD:$PWD --workdir $PWD'
alias dks='docker stop'

alias dklc='docker ps -l'                                                            # List last Docker container'
alias dklcid='docker ps -l -q'                                                       # List last Docker container ID'
alias dklcip='docker inspect -f "{{.NetworkSettings.IPAddress}}" $(docker ps -l -q)' # Get IP of last Docker container'
alias dkps='docker ps'                                                               # List running Docker containers'
alias dkpsa='docker ps -a'                                                           # List all Docker containers'
alias dki='docker images'                                                            # List Docker images'
alias dkrm='docker rm'
alias dkrmf='docker rm --force'
alias dkri='docker rmi'
alias dkrmac='docker rm $(docker ps -a -q)'                                          # Delete all Docker containers'
alias dkrmlc='docker-remove-most-recent-container'                                   # Delete most recent (i.e., last) Docker container'
alias dkrmui='docker images -q -f dangling=true |xargs docker rmi'                   # Delete all untagged Docker images'
alias dkrmall='docker-remove-stale-assets'                                           # Delete all untagged images and exited containers'
alias dkrmli='docker-remove-most-recent-image'                                       # Delete most recent (i.e., last) Docker image'
alias dkrmi='docker-remove-images'                                                   # Delete images for supplied IDs or all if no IDs are passed as arguments'
alias dkideps='docker-image-dependencies'                                            # Output a graph of image dependencies using Graphiz'
alias dkre='docker-runtime-environment'                                              # List environmental variables of the supplied image ID'
alias dkelc='docker exec -it `dklcid` bash'                                          # Enter last container (works with Docker 1.3 and above)'
alias dkvl='docker volume ls'
alias dkvr='docker volume rm'
