#!/usr/bin/env bash

# Follow fugitive-:Gstatus
alias gca='git commit --amend'
alias gcc='git commit -v'
alias gce='git commit --amend --no-edit'
alias gcw='git commit --amend --only'
alias gcva='git commit --verbose --amend'
alias gcvc='git commit --verbose'

# Enhancement

alias gl='git pull --prune'

alias ga.='git add .'
alias gau='git add --update'
alias gbb='git bisect bad'
alias gbg='git bisect good'
alias gbs='git bisect start'
alias gbr='git bisect reset'
alias gcf='git commit --fixup'
alias gcfh='git commit --fixup HEAD'
alias gcl1='git clone --depth=1'
alias gco-='git checkout -'
alias gco.='git checkout .'
alias gcop='git checkout -p'
alias gds='git diff --staged'
alias ggr='git grep'
alias gia='git init && git commit --allow-empty --message "Initialize empty Git repository" && git add . && git commit'
alias gic='git init && git commit --allow-empty --message "Initialize empty Git repository"'
alias gmt='git mergetool'
alias gpof='git push origin -f'
alias gpoh='git push origin HEAD:'
alias gpohm='git push origin HEAD:master'
alias gpuof='git push --set-upstream origin --force'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase --interactive'
alias grbk='git rebase --skip'
alias grbm='git rebase origin/master'
alias grbo='git rebase --onto'
alias grbs='git rebase --autosquash --interactive'
alias grbu='git fetch origin -v; git fetch upstream -v; git merge upstream/master'
alias grf='git reflog --date=relative'
alias grs^='git reset HEAD^'
alias grsh='git reset --hard'
alias grsm='git reset --merge'
alias gsh='git show'
alias gstd='git stash drop'
alias gstk='git stash --keep-index'
alias gstP='git stash pop'
alias gstp='git stash push'
alias gsts='git stash show --patch'
