alias homecd='cd  ~/git/github.com/sharils/home/'
alias homedit='vim ~/git/github.com/sharils/home/install'
alias homepull='cd ~/git/github.com/sharils/home && git stash push && git pull --prune && vim -S ~/.vim/snapshot.vim && cd - && bash-it reload'
alias homepush='cd ~/git/github.com/sharils/home && git push && cd -'
alias homeupdate='bash-it update && hr ♾ && rustup update && hr ♾ && brew upgrade && hr ♾ && brew cask upgrade && noti'
alias homevupdate='vim +PlugUpdate && vim +"PlugSnapshot! ~/.vim/snapshot.vim" && cd ~/git/github.com/sharils/home && git add .vim/snapshot.vim && git commit -m "Pump vim plugin verions" && git push'
