alias na='npm audit'
alias naf='npm audit fix'
alias nb='npm build'
alias nci='npm ci'
alias ncl='rm -fr ./node_modules'
alias ngi='npm --global install'
alias ngls='npm --global list --depth=0'
alias ngrm='npm --global rm'
alias niy='npm init --yes'
alias nrm='npm rm'
alias ns='npm start'
alias nsr='npm search'
alias nt='npm test'
alias nv='npm view'
