#!/usr/bin/env bash

alias vims='vim -S'
alias vimbash='vim /tmp/$RANDOM.bash'
alias vimc='vim /tmp/$RANDOM.c'
alias vimcss='vim /tmp/$RANDOM.css'
alias vimerl='vim /tmp/$RANDOM.erl'
alias vimex='vim /tmp/$RANDOM.ex'
alias vimexs='vim /tmp/$RANDOM.exs'
alias vimhtml='vim /tmp/$RANDOM.html'
alias vimjava='vim /tmp/$RANDOM.java'
alias vimjs='vim /tmp/$RANDOM.js'
alias vimjson='vim /tmp/$RANDOM.json'
alias vimlua='vim /tmp/$RANDOM.lua'
alias vimmd='vim /tmp/$RANDOM.md'
alias vimphp='vim /tmp/$RANDOM.php'
alias vimpy='vim /tmp/$RANDOM.py'
alias vimrs='vim /tmp/$RANDOM.rs'
alias vimsh='vim /tmp/$RANDOM.sh'
alias vimsql='vim /tmp/$RANDOM.sql'
alias vimt='vim /tmp/$RANDOM'
alias vimtxt='vim /tmp/$RANDOM.txt'
alias vimzep='vim /tmp/$RANDOM.zep'
