#!/usr/bin/env bash

alias vims='vim -S'
alias vimtmp='vim /tmp/'
alias vimt='vim /tmp/$RANDOM'

alias vimbash='vim /tmp/$RANDOM.bash'
alias vimc='vim /tmp/$RANDOM.c'
alias vimcss='vim /tmp/$RANDOM.css'
alias vimdk='vim /tmp/$RANDOM.Dockerfile'
alias vimeex='vim /tmp/$RANDOM.eex'
alias vimerl='vim /tmp/$RANDOM.erl'
alias vimex='vim /tmp/$RANDOM.ex'
alias vimexs='vim /tmp/$RANDOM.exs'
alias vimhtml='vim /tmp/$RANDOM.html'
alias vimjava='vim /tmp/$RANDOM.java'
alias vimjs='vim /tmp/$RANDOM.js'
alias vimjson='vim /tmp/$RANDOM.json'
alias vimjsx='vim /tmp/$RANDOM.jsx'
alias vimlua='vim /tmp/$RANDOM.lua'
alias vimmd='vim /tmp/$RANDOM.md'
alias vimphp='vim /tmp/$RANDOM.php'
alias vimpy='vim /tmp/$RANDOM.py'
alias vimrc='vim ~/.vimrc'
alias vimrs='vim /tmp/$RANDOM.rs'
alias vimsh='vim /tmp/$RANDOM.sh'
alias vimsql='vim /tmp/$RANDOM.sql'
alias vimstory='vim /tmp/$RANDOM.story'
alias vimtxt='vim /tmp/$RANDOM.txt'
alias vimyml='vim /tmp/$RANDOM.yml'
alias vimzep='vim /tmp/$RANDOM.zep'
