#!/usr/bin/env bash
# shellcheck disable=SC2139

alias vss='vim -S Session.vim'

alias vpc='vim +PlugClean'
alias vpi='vim +PlugInstall'
alias vps="vim +'PlugSnapshot! ~/.vim/snapshot.vim'"
alias vpu='vim +PlugUpdate'

alias vbh='vim ~/.bash_history'
alias vdco='vim docker-compose.yml'
alias vdk='vim Dockerfile'
alias verc='vim .envrc'
alias vgi='vim .gitignore'
alias vgie='vim .git/info/exclude'
alias vic='vim index.css'
alias vih='vim index.html'
alias vij='vim index.js'
alias vijsx='vim index.jsx'
alias vmf='vim Makefile'
alias vnc='vim next.config.js'
alias vpj='vim package.json'
alias vrm='vim README.md'
alias vsj='vim server.js'
alias vtigrc='vim ~/.tigrc'
alias vtorrc='vim ~/Library/Application\ Support/TorBrowser-Data/Tor/torrc'
alias vvrc='vim ~/git/github.com/sharils/home/.vimrc'

alias vt="vim /tmp/$USER-$RANDOM"
alias vbash="vim /tmp/bash-$USER-$RANDOM.bash"
alias vc="vim /tmp/c-$USER-$RANDOM.c"
alias vcss="vim /tmp/css-$USER-$RANDOM.css"
alias vscss="vim /tmp/scss-$USER-$RANDOM.scss"
alias veex="vim /tmp/eex-$USER-$RANDOM.eex"
alias verl="vim /tmp/erl-$USER-$RANDOM.erl"
alias vex="vim /tmp/ex-$USER-$RANDOM.ex"
alias vexs="vim /tmp/exs-$USER-$RANDOM.exs"
alias vhtml="vim /tmp/html-$USER-$RANDOM.html"
alias vjava="vim /tmp/java-$USER-$RANDOM.java"
alias vjq="vim /tmp/jq-$USER-$RANDOM.jq"
alias vjs="vim /tmp/js-$USER-$RANDOM.js"
alias vjson="vim /tmp/json-$USER-$RANDOM.json"
alias vjsx="vim /tmp/jsx-$USER-$RANDOM.jsx"
alias vlua="vim /tmp/lua-$USER-$RANDOM.lua"
alias vmd="vim /tmp/md-$USER-$RANDOM.md"
alias vpegjs="vim /tmp/php-$USER-$RANDOM.pegjs"
alias vphp="vim /tmp/php-$USER-$RANDOM.php"
alias vpy="vim /tmp/py-$USER-$RANDOM.py"
alias vrs="vim /tmp/rs-$USER-$RANDOM.rs"
alias vsh="vim /tmp/sh-$USER-$RANDOM.sh"
alias vsql="vim /tmp/sql-$USER-$RANDOM.sql"
alias vstory="vim /tmp/story-$USER-$RANDOM.story"
alias vts="vim /tmp/ts-$USER-$RANDOM.ts"
alias vtxt="vim /tmp/txt-$USER-$RANDOM.txt"
alias vxhtml="vim /tmp/html-$USER-$RANDOM.xhtml"
alias vyml="vim /tmp/yml-$USER-$RANDOM.yml"
alias vyaml="vim /tmp/yaml-$USER-$RANDOM.yaml"
alias vzep="vim /tmp/zep-$USER-$RANDOM.zep"
